# Generated by Django 4.2.5 on 2023-11-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_listingmodels_word_listingmodels_works'),
    ]

    operations = [
    ]
